// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactRelay = require("react-relay");

function make(environment, query, render, variables, children) {
  return ReasonReact.wrapJsForReason(ReactRelay.QueryRenderer, {
              environment: environment,
              query: query,
              render: render,
              variables: variables
            }, children);
}

var QueryRenderer = /* module */[/* make */make];

var house = {
  name: "Lorenzo",
  age: 24,
  job: "Developer"
};

var name = house.name;

exports.QueryRenderer = QueryRenderer;
exports.house = house;
exports.name = name;
/* name Not a pure module */
